<!DOCTYPE html>
<html>
<head>
    <title>Manager Dashboard Report</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .header {
            border-bottom: 2px solid #3376f2;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 20px;
            margin: 0;
            color: #3376f2;
        }
        .section {
            margin-bottom: 25px;
        }
        .section-title {
            font-weight: bold;
            text-transform: uppercase;
            font-size: 14px;
            color: #555;
            margin-bottom: 8px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 3px;
        }
        .data-list {
            list-style-type: none;
            padding-left: 0;
            margin: 0;
        }
        .data-item {
            font-size: 13px;
            margin-bottom: 5px;
        }
        .footer {
            margin-top: 50px;
            font-size: 10px;
            color: #888;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Manager's Dashboard Report - {{ $reportDate }}</h1>
    </div>

    <div class="section">
        <div class="section-title">OCCUPANCY & COMPLIANCE</div>
        <ul class="data-list">
            <li class="data-item">- Beds Occupied: {{ $occupancy['bedsOccupied'] }}/{{ $occupancy['totalBeds'] }} ({{ $occupancy['percentage'] }}%)</li>
        </ul>
    </div>

    <div class="section">
        <div class="section-title">STAFF MANAGEMENT</div>
        <ul class="data-list">
            <li class="data-item">- Today's Shifts: {{ $staffManagement['todayShifts'] }}</li>
            <li class="data-item">- Unfilled Shifts: {{ $staffManagement['unfilledShifts'] }}</li>
            <li class="data-item">- Fill Rate: {{ $staffManagement['fillRate'] }}%</li>
        </ul>
    </div>

    <div class="section">
        <div class="section-title">TRAINING COMPLIANCE</div>
        <ul class="data-list">
            <li class="data-item">- Completion Rate: {{ number_format($training['completionRate'], 1) }}%</li>
            <li class="data-item">- Expiring Certificates: {{ $training['expiring'] }}</li>
            <li class="data-item">- Overdue Training: {{ $training['overdue'] }}</li>
        </ul>
    </div>

    <div class="section">
        <div class="section-title">INCIDENTS & SAFETY</div>
        <ul class="data-list">
            <li class="data-item">- Recent Incidents: {{ $incidents['recent'] }}</li>
            <li class="data-item">- Unresolved: {{ $incidents['unresolved'] }}</li>
            <li class="data-item">- Critical: {{ $incidents['critical'] }}</li>
        </ul>
    </div>

    <div class="section">
        <div class="section-title">COMMUNICATION</div>
        <ul class="data-list">
            <li class="data-item">- Pending Leave Requests: {{ $communication['pendingLeave'] }}</li>
            <li class="data-item">- New Feedback: {{ $communication['newFeedback'] }}</li>
            <li class="data-item">- Critical Alerts: {{ $communication['criticalAlerts'] }}</li>
        </ul>
    </div>

    <div class="footer">
        Generated by Social Care IT Solutions - {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
