<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; color: #333; line-height: 1.6; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        h2 { color: #2c3e50; }
        .message-body { background: #f8f9fa; border-radius: 6px; padding: 15px 20px; margin: 20px 0; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #eee; font-size: 12px; color: #999; }
    </style>
</head>
<body>
<div class="container">
    <h2>{{ $workflowName }}</h2>
    <p>An automated workflow has been triggered on {{ now()->format('d M Y \a\t H:i') }}.</p>

    <div class="message-body">
        {{ $messageBody }}
    </div>

    <div class="footer">
        Generated by Care OS Workflow Automation &mdash; Omega Life UK
    </div>
</div>
</body>
</html>
